language: java

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script: ./gradlew bootJar

    - stage: deploy
      if: branch = develop
      script: ./gradlew jib -Djib.to.auth.username=${DOCKER_HUB_USERNAME} -Djib.to.auth.password=${DOCKER_HUB_PASSWORD}



