spring:
  rabbitmq:
    host: rabbit
    port: 5671
    ssl:
      enabled: true
      algorithm: TLSv1.2

  influx:
    url: http://influx:8086

  data:
    mongodb:
      host: mongo
      database: cloudio

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudio
    username: cloudio
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
