spring:
  profiles:
    active: ["default", "rest-api"]

  main:
    web-application-type: none

  rabbitmq:
    host: rabbit
    port: 5671
    ssl:
      enabled: true
      algorithm: TLSv1.2
      key-store: '@generate'
      trust-store: '@generate'

  influx:
    url: http://influx:8086

  datasource:
    url: jdbc:postgresql://database:5432/cloudio
    username: cloudio

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher