version: '3.7'
services:
  rabbitmq:
    image: cloudio/cloudio-rabbitmq:3.9.22-1
    ports:
    - "8883:8883"
    - "5671:5671"
    - "15672:15672"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CA_CERT: ${CA_CERT}
      SERVER_CERT: ${SERVER_CERT}
      SERVER_KEY: ${SERVER_KEY}

  influx:
    image: influxdb:2.6.1
    ports:
    - "8086:8086"

  database:
    image: postgres:14.5-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: cloudio
      POSTGRES_DB: cloudio
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql