version: '3.7'
services:
  rabbitmq:
    image: cloudio/cloudio-rabbitmq:latest
    ports:
    - "8883:8883"
    - "5671:5671"
    - "15672:15672"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CA_CERT: ${CA_CERT}
      SERVER_CERT: ${SERVER_CERT}
      SERVER_KEY: ${SERVER_KEY}

  influx:
    image: influxdb:latest
    ports:
    - "8086:8086"

  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    
  cloudio-service:
    image: cloudio/cloudio-services:0.2.0-SNAPSHOT 
    ports:
    - "8081:8081"
    network_mode: "host"
    environment:
      spring.rabbitmq.username: 'admin'
      spring.rabbitmq.password: ${ADMIN_PASSWORD}
      spring.rabbitmq.host: '127.0.0.1' 
      spring.rabbitmq.port: '5671'
      spring.rabbitmq.ssl.enabled: 'true'
      spring.rabbitmq.ssl.algorithm: 'TLSv1.2'
      spring.rabbitmq.ssl.verify-hostname: 'false'
      spring.rabbitmq.ssl.validate-server-certificate: 'false'
      spring.influx: 'http://127.0.0.1:8086'
      spring.data.mongodb.host: '127.0.0.1'
      spring.data.mongodb.database: 'cloudio'
      server.port: '8081'
      cloudio.cert-manager.caCertificate: ${CA_CERT}
      cloudio.cert-manager.caPrivateKey: ${CA_KEY}
    
