version: '3.7'
services:
  rabbitmq:
    image: cloudio/cloudio-rabbitmq:latest
    ports:
    - "8883:8883"
    - "5671:5671"
    - "15672:15672"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CA_CERT: ${CA_CERT}
      SERVER_CERT: ${SERVER_CERT}
      SERVER_KEY: ${SERVER_KEY}

  influx:
    image: influxdb:2.1-alpine
    ports:
    - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: cloudio
      DOCKER_INFLUXDB_INIT_BUCKET: system
      DOCKER_INFLUXDB_INIT_USERNAME: cloudio
      DOCKER_INFLUXDB_INIT_PASSWORD: ${ADMIN_PASSWORD}

  database:
    image: postgres:12.2-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: cloudio
      POSTGRES_DB: cloudio
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql