package ch.hevs.cloudio.cloud.model

enum class Authority {
    BROKER_ACCESS,
    BROKER_MANAGEMENT_POLICYMAKER,
    BROKER_MANAGEMENT_MONITORING,
    BROKER_MANAGEMENT_ADMINISTRATOR,

    HTTP_ACCESS,
    HTTP_ADMIN
}
